// Generated by CoffeeScript 1.8.0

/**
@author
@description
@name artistsController
 */


/* @ngInject */

(function() {
  module.exports = function($scope) {
    $scope.greeting = "Hello world from artistsController";
  };

}).call(this);
