// Generated by CoffeeScript 1.8.0

/**
@author
@description
@name songsController
 */


/* @ngInject */

(function() {
  module.exports = function($scope) {
    $scope.greeting = "Hello world from songsController";
  };

}).call(this);
